### ISSUE TITLE
This functionality will be in RainLab.User v1.1

### ISSUE THREAD

**Issue by daftspunk** [gabsource/usergroup-plugin#1]
FYI

https://github.com/rainlab/user-plugin/tree/1.1

**Comment by gabsource** [comment]
Thanks for pointing this, I did'nt figure it out.
This is mainly a test repo to play with plugin extensions. We were going to use https://github.com/Shahiem/frontend-roles-manager but the base plugin be be OK in 1.1 branch.

We are missing two features : 
- a translated plugin (front-end, back-end, emails) [FR]
- a component to filter a page access on groups the connected user belongs to (as Session component but only with group selection in the properties)

For now this is done in the project itself by overriding the partials for front-end translation and using a custom component for the acccess filter.

I have opened a PR for French translation on RainLab.User 1.1 : https://github.com/rainlab/user-plugin/pull/104
I also have a PR open for RainLab.Pages for French translation : https://github.com/rainlab/pages-plugin/pull/58

For front-end component and emails it's harder to provided a translation with the base plugin.
